/* ===== 預設示範資料（seed）=====
   換一團時只改這個檔：團名、日期、名單、行程、記事本。程式碼在 parts/ 不用動。
   正式使用時由領隊在管理模式修改，或由雲端資料覆蓋；這裡刻意不含任何電話。 */
var DEFAULTS = {
  photos:{items:{}},
  settings:{
    tripName:'沙壩雲海五日', startDate:'2026-09-24', days:5, dayOverride:0, pin:'8888',
    /* 領隊決定團員第一次看到時，卡片是展開(1)還是收起(0)；ts 變動時團員自己的選擇會重置 */
    cards:{prep:{o:1,ts:0},flight:{o:1,ts:0},morning:{o:1,ts:0},hotel:{o:0,ts:0}},
    /* 防呆標籤：領隊可自訂增減，改了全團同步 */
    tags:[
      {id:'coat',icon:'coat',label:'厚外套'},{id:'shoes',icon:'shoes',label:'防滑鞋'},{id:'toilet',icon:'toilet',label:'有洗手間'},
      {id:'rain',icon:'rain',label:'雨具'},{id:'meal',icon:'meal',label:'用餐'},{id:'ticket',icon:'ticket',label:'帶護照'},
      {id:'alt',icon:'mountain',label:'高海拔'},{id:'bus',icon:'bus',label:'長途車'},{id:'cash',icon:'cash',label:'備現金'},
      {id:'walk',icon:'walk',label:'步行多'},{id:'camera',icon:'camera',label:'拍照點'},{id:'pill',icon:'thermo',label:'易暈車'},
      {id:'bed',icon:'bed',label:'入住'}
    ],
    airlines:{eva:{short:'長榮',name:'長榮航空',note:'桃園第二航廈'},ci:{short:'華航',name:'中華航空',note:'桃園第一航廈'}},
    vndPerTwd:820,
    /* 電話刻意留白：正式版請領隊進管理模式 → 團務設定 填入，資料只存在同步後端，不會出現在原始碼 */
    contacts:[
      {name:'黃氏添',label:'越南電話',phone:'',line:''},
      {name:'黃氏添',label:'台灣電話',phone:'',line:''},
      {name:'麥松華',label:'台灣電話',phone:'',line:''}
    ],
    flights:{ ci:{out:'08:20',back:'11:30'}, eva:{out:'09:00',back:'12:05'}, note:'團體報到：全體 05:30 在桃園第二航廈集合（不分航空公司）。分發護照與行李吊牌後，華航團員一起搭免費電車到第一航廈辦登機，長榮團員留在第二航廈。' },
    embassyPhone:'+84913219986',
    currentHotelId:'sapa',
    hotels:[
      {id:'sapa',name:"沙壩 Pao's Sapa Leisure Hotel",nameVi:"Khách sạn Pao's Sapa Leisure",addrVi:'Tổ dân phố Cầu Mây 1, Sa Pa, Lào Cai 31752, Việt Nam',phone:'',wifi:'入住時公布',wifiPass:'入住時公布',wifiNote:'連不上請到櫃台問，或跟領隊說。',breakfast:'06:00–09:00',leaderRoom:'',nights:'第 1、2、3 晚'},
      {id:'train',name:'夜臥火車 Chapa Express',nameVi:'Tàu Chapa Express · Ga Lào Cai',addrVi:'Ga Lào Cai, Phố Mới, TP. Lào Cai, Lào Cai',phone:'',wifi:'車上沒有 Wi-Fi',wifiPass:'',wifiNote:'火車上沒有 Wi-Fi，請先在飯店把要看的東西下載好。',breakfast:'車上不供餐，抵達河內後用早餐',leaderRoom:'',nights:'第 4 晚（老街 → 河內）'}
    ],
    morning:{wake:'',breakfast:'',luggage:'',depart:'',note:'領隊每晚會在這裡公布明早時間。'}
  },
  broadcast:{ time:'', label:'集合', location:'', tip:'', idle:false, updatedAt:'' },
  itinerary:{ items:[
    /* ===== 第 1 天 9/24（三）桃園 → 河內 → 沙壩 ===== */
    {id:'d1a',day:1,place:'Taoyuan International Airport Terminal 2',time:'05:30',title:'桃園機場集合',
     desc:'全體不分航空公司，05:30 在第二航廈集合。',
     detail:'請提早出門，05:30 準時到第二航廈出境大廳，領隊會發護照與行李吊牌。\n液體超過 100ml 一律託運；行動電源、鋰電池必須隨身，不可以放託運行李。\n手機記得充飽電，並帶一條充電線與轉接頭（越南是雙圓孔，台灣扁插頭多半可以直接用）。',
     tags:['ticket','toilet']},
    {id:'d1b',day:1,place:'Taoyuan International Airport Terminal 1',time:'06:00',title:'分頭辦登機',
     desc:'🔴 華航團員搭電車到第一航廈；🟢 長榮團員留在第二航廈。',
     detail:'兩航廈間的免費電車約 5 分鐘一班、車程 2 分鐘，跟著領隊走不會迷路。\n辦完登機各自過安檢，登機門看登機證上的號碼。\n過安檢後如果找不到人，直接看本網頁的「緊急求助」打電話，不要自己亂走。',
     tags:['ticket','walk']},
    {id:'d1c',day:1,place:'Noi Bai International Airport',time:'11:15',title:'河內機場會合',
     desc:'華航約 10:30、長榮約 11:15 抵達，先到的在行李轉盤外等。',
     detail:'越南時間比台灣慢 1 小時，下機後請確認手機時間已自動調整；本網頁所有時間都是越南當地時間。\n入境要出示護照與越南電子簽證列印本，請放在隨身包好拿的地方。\n領完行李在出關大廳等全員到齊，導遊會舉牌接機。',
     tags:['ticket','bus']},
    {id:'d1d',day:1,place:'Sa Pa, Lao Cai, Vietnam',time:'12:00',title:'出發前往沙壩',
     desc:'車程約 6 小時，中途休息站停 2 次可上洗手間。',
     detail:'河內到沙壩約 320 公里，走高速公路約 5.5～6 小時，是這趟最長的一段車程。\n容易暈車的人請在上車前 30 分鐘先吃暈車藥，坐前排、看遠方、少滑手機。\n山路後半段彎道多，隨身行李請放腳邊或行李架綁好。\n休息站有洗手間但不一定有衛生紙，請自備一小包。',
     tags:['bus','pill','toilet']},
    {id:'d1e',day:1,place:"Pao's Sapa Leisure Hotel, To dan pho Cau May 1, Sa Pa, Lao Cai",time:'18:00',title:'抵達沙壩入住',
     desc:"入住 Pao's Sapa Leisure Hotel，領隊發房卡。",
     detail:'沙壩海拔約 1,500 公尺，晚上常降到 15 度以下，下車第一件事就是把外套拿出來。\n進房先確認：熱水、吹風機、插座、保險箱。有問題馬上跟領隊說，不要忍到隔天。\n這間飯店會住 3 個晚上（9/24、9/25、9/26），行李可以整個攤開，不用每天收。',
     tags:['bed','coat']},
    {id:'d1f',day:1,time:'19:00',title:'晚餐：飯店',
     desc:'第一晚在飯店內用餐，餐後早點休息。',
     detail:'今天坐了一整天車，晚餐後建議早點睡，讓身體適應高度與溫差。\n山上空氣乾，睡前多喝一點溫水。',
     tags:['meal']},

    /* ===== 第 2 天 9/25（四）番西邦峰・貓貓村 ===== */
    {id:'d2a',day:2,time:'06:00',title:'早餐：飯店',
     desc:'飯店內自助早餐，06:00–08:00。',
     detail:'今天要上番西邦峰，早餐請吃飽一點，山頂餐廳選擇不多。\n建議帶一顆水煮蛋或麵包上山備用。',
     tags:['meal']},
    {id:'d2b',day:2,place:'Sun World Fansipan Legend',time:'08:00',title:'番西邦峰纜車',
     desc:'搭三索纜車直上「印度支那屋脊」，俯瞰梯田雲海。',
     detail:'番西邦峰海拔 3,143 公尺，是中南半島最高峰。纜車全長 6.3 公里，約 15 分鐘直達上站。\n山頂比沙壩鎮再冷 5～8 度，而且風大，厚外套一定要帶著，不要放在車上。\n上站到峰頂還有 600 階石梯，走不動的人可以加購山頂纜車（單程約 150,000 越盾），或在觀景平台等大家，不要勉強。\n高海拔容易喘、頭暈，慢慢走、多休息；有心臟或高血壓問題的長輩請先告訴領隊。\n山上雲霧變化很快，看到雲海就先拍，不要等下一個點。',
     tags:['coat','alt','shoes','camera','toilet']},
    {id:'d2c',day:2,place:'33 Hoang Lien, Sa Pa, Lao Cai',time:'11:30',title:'午餐：越式合菜',
     desc:'Viet Trekking 餐廳，越式合菜（番西邦套餐）。',
     detail:'地址：33 Hoàng Liên, Sa Pa, Lào Cai，就在鎮上主要道路旁。\n吃素或有忌口的人請在上車前先告訴領隊，餐廳需要提前備料。',
     tags:['meal']},
    {id:'d2d',day:2,place:'Cat Cat Village, Sa Pa',time:'13:30',title:'貓貓村健行',
     desc:'沿石板步道下坡穿過梯田、水車與法國時期小水電站。',
     detail:'貓貓村（Cát Cát）是黑苗族的村落，距沙壩鎮約 2 公里，全程下坡約 1.5 公里。\n石板路走多了會滑，尤其下過雨之後，請穿防滑的鞋子，不要穿新鞋或涼鞋。\n回程是上坡，走不動可以在村口叫摩托計程車（約 50,000 越盾）回鎮上，先跟領隊說一聲。\n村裡的苗族婦女會跟著你兜售手工藝品，不想買就微笑說「không, cảm ơn」（不用了，謝謝）並繼續走，不要停下來翻看。\n拍照前請先問一下，尤其是拍人。',
     tags:['shoes','walk','rain','camera','cash']},
    {id:'d2e',day:2,place:'Sa Pa Xua Restaurant, Sa Pa',time:'17:30',title:'晚餐：夜市旁餐廳',
     desc:'Sapa Xưa，沙壩夜市正對面，用餐到 22:00。',
     detail:'地址：SN 005, Đường N02（Đỗ Quyên），沙壩夜市正對面。\n山上腸胃比較敏感，生食與冰飲建議少碰，多喝溫的。\n餐後走幾步就是夜市，想逛的人跟領隊說一聲，回飯店的路只有 5 分鐘，但天黑後路燈不多，兩人以上一起走。',
     tags:['meal','cash','coat']},

    /* ===== 第 3 天 9/26（五）達灣・按摩・廣場 ===== */
    {id:'d3a',day:3,time:'06:00',title:'早餐：飯店',
     desc:'飯店內自助早餐，06:00–09:00。',
     detail:'今天行程比較輕鬆，可以睡晚一點再下樓。',
     tags:['meal']},
    {id:'d3b',day:3,place:'Ta Van Village, Sa Pa',time:'09:00',title:'達灣梯田村',
     desc:'達灣 Tả Van，沙壩最美的梯田村落。',
     detail:'達灣（Tả Van）在沙壩鎮東南約 10 公里的山谷裡，是整個沙壩梯田風景最完整的一段。\n九月底正好是稻穗轉金黃的時候，這裡是全程最值得拍照的地方。\n田埂路窄又可能有泥，請走在導遊指定的路線上，不要為了取景走進田裡。\n村裡有吊橋，一次不要太多人上去，過橋時扶好欄杆。\n山谷訊號較弱，跟大家走在一起，不要落單。',
     tags:['walk','shoes','camera','rain']},
    {id:'d3c',day:3,place:'Sailing Ta Van, Sa Pa',time:'11:30',title:'午餐：達灣景觀',
     desc:'Sailing Ta Van，梯田景觀餐廳。',
     detail:'餐廳有大片落地窗看得到整片梯田，早到的人可以先去露台拍照。\n吃素或有忌口的人請提前告訴領隊。',
     tags:['meal','camera']},
    {id:'d3d',day:3,time:'14:00',title:'自由按摩行程',
     desc:'下午自由安排，可以做腳底或全身按摩。',
     detail:'走了兩天山路，這個下午是特地留給大家休息的。\n沙壩鎮上的按摩店行情：腳底 60 分鐘約 200,000～300,000 越盾，全身約 350,000～450,000 越盾，記得先問價再進去。\n有高血壓、心臟病、剛開過刀或懷孕的人，請避免全身重壓的按摩。\n不想按摩的人可以留在飯店休息，或到廣場附近喝咖啡，晚餐前回到飯店集合。',
     tags:['cash','pill']},
    {id:'d3e',day:3,place:'Nha hang O Quy Ho, Sa Pa',time:'17:30',title:'晚餐：山區風味',
     desc:'Nhà hàng Ô Quý Hồ，沙壩山區特色料理。',
     detail:'沙壩的高山冷水養殖鮭魚是當地招牌，跟海水鮭魚口感不同，值得試試。\n這一帶的菜偏酸辣，怕辣的人點餐時說「không cay」（不要辣）。\n山上的雞湯與燉品很適合長輩，可以多喝一點湯暖身。',
     tags:['meal']},
    {id:'d3f',day:3,place:'Sa Pa Square, Sa Pa',time:'19:30',title:'廣場自由活動',
     desc:'飯後可以到廣場喝咖啡、逛街，21:30 前回飯店。',
     detail:'沙壩廣場與石教堂就在飯店步行 5～10 分鐘範圍內，晚上有當地人跳廣場舞，很熱鬧。\n越南咖啡很濃，晚上喝建議點一杯就好，或改點椰子咖啡。\n夜市與路邊攤開價通常可以殺 3～5 成，慢慢殺不要急。\n山上晚上溫差大，出門一定要加件外套。\n找不到路回飯店就打開本網頁的「計程車回飯店卡」給司機或路人看。',
     tags:['walk','cash','coat']},

    /* ===== 第 4 天 9/27（六）飯店設施・老街・夜臥火車 ===== */
    {id:'d4a',day:4,time:'06:00',title:'早餐：飯店',
     desc:'飯店內自助早餐，06:00–09:00。今天要退房。',
     detail:'今晚睡火車，早餐後請先把行李整理好，該託運的、隨身的分開裝。',
     tags:['meal','bed']},
    {id:'d4b',day:4,time:'08:00',title:'飯店設施自由',
     desc:'自由使用飯店設施，或自費去玻璃橋。',
     detail:'玻璃橋（Rồng Mây 龍雲玻璃橋）在沙壩往萊州的公路上，車程約 40 分鐘，門票需自費。\n想去的人請在前一晚跟領隊登記，人數夠才會安排車輛。\n懼高、有心臟病或高血壓的長輩不建議前往。\n不去的人可以留在飯店泡湯、泡咖啡，或到附近散步，12:00 前回房間收行李。',
     tags:['cash','camera']},
    {id:'d4c',day:4,place:"Pao's Sapa Leisure Hotel, To dan pho Cau May 1, Sa Pa, Lao Cai",time:'12:00',title:'退房・寄行李',
     desc:'12:00 退房，行李統一寄放在飯店。',
     detail:'退房前請務必檢查：保險箱（很多人把護照忘在裡面）、浴室、床頭櫃、插座上的充電器。\n退房後行李寄放在飯店大廳，下午還可以自由活動，16:00 上車前再一起取。\n護照、錢包、藥品、當晚換洗衣物請放隨身包，不要放進寄放的大行李。',
     tags:['bed','ticket']},
    {id:'d4d',day:4,place:'22 Ngu Chi Son, Sa Pa, Lao Cai',time:'12:30',title:'午餐：沙壩最後',
     desc:'Chạm Quán Sapa - Restaurant & Drinks。',
     detail:'地址：22 Ngũ Chỉ Sơn, Sa Pa, Lào Cai。\n吃完飯後鎮上還有時間可以買伴手禮：竹筒飯、山茶、乾燥草藥包、苗族刺繡都是這裡的特產。\n剩下的越盾建議在沙壩花掉，火車站與機場的東西比較貴。',
     tags:['meal','cash']},
    {id:'d4e',day:4,place:'Lao Cai Railway Station',time:'16:00',title:'前往老街站',
     desc:'搭車下山到老街火車站，車程約 1 小時。',
     detail:'從沙壩下到老街市區約 35 公里、車程 1 小時，全程下坡彎道多，容易暈車的人請先吃藥。\n老街市就在中越邊境旁，可以看到對岸的中國河口。\n到了火車站先上洗手間，火車上的洗手間比較克難。',
     tags:['bus','pill','toilet']},
    {id:'d4f',day:4,time:'19:00',title:'晚餐：老街',
     desc:'在老街市區用晚餐，之後前往月台候車。',
     detail:'上車前請把水裝滿、想吃的零食先買好，火車上沒有餐車。\n建議先換上舒服好睡的衣服。',
     tags:['meal']},
    {id:'d4g',day:4,place:'Lao Cai Railway Station',time:'21:30',title:'搭夜臥火車',
     desc:'Chapa Express 臥鋪，21:30 發車，隔天 05:30 抵達河內。',
     detail:'搭的是 Chapa Express 觀光臥鋪列車，四人一間的上下舖，領隊會分配舖位，行李放在下舖底下或走道行李架。\n上舖有爬梯，長輩請睡下舖，上車先跟領隊講。\n貴重物品（護照、錢包、手機）請放在枕頭邊或隨身腰包，不要放在走道上。\n火車會搖晃且有聲音，帶耳塞和眼罩會好睡很多。\n車廂冷氣偏強，睡覺記得蓋好被子或加件外套。\n洗手間在車廂兩端，晚上走動請扶著扶手。',
     tags:['bed','coat','toilet','ticket']},

    /* ===== 第 5 天 9/28（日）河內 → 桃園 ===== */
    {id:'d5a',day:5,place:'Hanoi Railway Station',time:'05:30',title:'抵達河內',
     desc:'05:30 抵達河內火車站，清點行李下車。',
     detail:'下車前請把舖位、行李架、枕頭底下再檢查一次，火車靠站時間短，東西掉了很難找回來。\n月台燈光昏暗，請跟緊領隊，慢慢走不要趕。',
     tags:['ticket','walk']},
    {id:'d5b',day:5,time:'06:00',title:'早餐：河粉',
     desc:'河內道地牛肉河粉（Phở），這趟最後一餐越南味。',
     detail:'河粉配的生菜與豆芽是生的，腸胃敏感的人可以不要放。\n桌上的辣椒醬與魚露請先沾一點試味道，越南魚露比台灣的鹹。\n吃完可以買一杯越南煉乳咖啡在車上喝。',
     tags:['meal']},
    {id:'d5c',day:5,place:'Noi Bai International Airport Terminal 2',time:'08:00',title:'前往內排機場',
     desc:'車程約 45 分鐘，剩餘越盾可在機場花掉。',
     detail:'越盾出境後幾乎換不回來，也不好用，請在機場免稅店或便利商店花完。\n機場有賣咖啡、腰果、椰子糖，是常見的伴手禮。\n手推車在航廈外就有，長輩的行李可以先放上去。',
     tags:['cash','bus']},
    {id:'d5d',day:5,place:'Noi Bai International Airport Terminal 2',time:'09:00',title:'辦登機託運',
     desc:'🔴 華航、🟢 長榮分別到各自櫃檯，領隊統一辦理。',
     detail:'請把護照與登機證拿在手上，不要收進行李。\n買的山茶、草藥、水果乾請放託運；打火機不能託運也不能隨身（越南規定較嚴，建議直接丟掉）。\n過海關後在登機門附近等，不要走太遠去逛免稅店。',
     tags:['ticket']},
    {id:'d5e',day:5,time:'11:30',title:'華航起飛回台',
     desc:'11:30 起飛，台灣時間約 15:45 抵達桃園第一航廈。',
     detail:'領完行李在入境大廳解散，回程請注意台灣的天氣與交通。',
     tags:['ticket']},
    {id:'d5f',day:5,time:'12:05',title:'長榮起飛回台',
     desc:'12:05 起飛，台灣時間約 16:20 抵達桃園第二航廈。',
     detail:'領完行李在入境大廳解散，辛苦大家了，平安回家。',
     tags:['ticket']}
  ]},
  members:{ items:[
    {id:'m01',name:'麥松華',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m02',name:'黃氏添',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m03',name:'黃玉杏',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m04',name:'李智弘',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m05',name:'賴維宏',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m06',name:'蔣秋銀',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m07',name:'王宏盟',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m08',name:'王郁宣',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m09',name:'張程豪',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m10',name:'王郁雯',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m11',name:'林秀玉',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m12',name:'洪水清',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m13',name:'劉月芬',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m14',name:'鄭麗卿',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m15',name:'謝宛頤',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m16',name:'梁惠卿',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m17',name:'麥瑀倩',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m18',name:'楊睿智',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m19',name:'林登祥',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m20',name:'林瓊暖',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m21',name:'林韋臻',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m22',name:'何賢杰',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m23',name:'周珀芬',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m24',name:'吳佩蓉',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m25',name:'鄭美環',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m26',name:'陳佳慧',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m27',name:'王文俊',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m28',name:'王峯良',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m29',name:'林坤宏',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m30',name:'孫武雄',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m31',name:'施佳伃',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m32',name:'施佳如',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''},
    {id:'m33',name:'鐘立承',emoji:'',bg:'bg-white',border:'bd-grey',remark:'',room:'',phone:'',airline:''}
  ]},
  groups:{ activeId:'meal', scenarios:[
    {id:'meal',name:'用餐分桌',count:4,names:['第 1 桌','第 2 桌','第 3 桌','第 4 桌'],assign:{},fixed:1,useTags:1,mtags:{},tagOpts:MEAL_TAGS.slice()},
    {id:'shuttle',name:'接駁車',count:2,names:['A 車','B 車'],assign:{}},
    {id:'hike',name:'健行分流',count:2,names:['健走組','咖啡悠閒組'],assign:{}}
  ]},
  rollcall:{ label:'', present:{}, startedAt:'' },
  /* 旅遊提醒記事本：內容全部由領隊即時編輯；勾選狀態只存在各自手機 */
  notebook:{ pages:[
    {id:'prep',icon:'🧳',title:'出發前準備',type:'check',items:[
      {id:'p00',kind:'head',text:'證件與錢'},
      {id:'p01',text:'護照（效期 6 個月以上）'},
      {id:'p02',text:'越南電子簽證列印本（姓名拼音要正確）'},
      {id:'p03',text:'護照影本＋2 吋照片 2 張'},
      {id:'p04',text:'現金：美金或台幣（換越盾用）'},
      {id:'p05',text:'信用卡 1～2 張'},
      {id:'p10',kind:'head',text:'衣物'},
      {id:'p11',text:'厚外套或羽絨背心（山頂約 10 度）'},
      {id:'p12',text:'薄長袖 + 短袖，洋蔥式穿法'},
      {id:'p13',text:'雨衣或折傘（午後常有雨）'},
      {id:'p14',text:'防滑好走的鞋'},
      {id:'p15',text:'帽子、圍巾、太陽眼鏡'},
      {id:'p20',kind:'head',text:'藥品與日用'},
      {id:'p21',text:'個人常備藥（放隨身包）'},
      {id:'p22',text:'暈車藥、腸胃藥、OK 繃、防蚊液'},
      {id:'p23',text:'保溫杯、口罩、濕紙巾、小包衛生紙'},
      {id:'p24',text:'老花眼鏡、備用眼鏡'},
      {id:'p30',kind:'head',text:'3C 與通訊'},
      {id:'p31',text:'越南網卡或 eSIM（已安裝並測試）'},
      {id:'p32',text:'行動電源（放隨身，不可託運）'},
      {id:'p33',text:'充電線、充電頭（越南 220V，多可直插）'},
      {id:'p34',text:'加入 LINE 群組、本網頁加到主畫面'}
    ]},
    {id:'basics',icon:'🏔️',title:'沙壩小常識',type:'notes',items:[
      {id:'b1',text:'🕐 越南比台灣慢 1 小時。本網頁所有時間都是沙壩當地時間，抬頭看右上角時鐘就對了。'},
      {id:'b2',text:'🌡️ 沙壩海拔 1,500 公尺、番西邦山頂 3,143 公尺，一天可以差 10 度以上；洋蔥式穿法最實用。'},
      {id:'b3',text:'🌦️ 9 月底的沙壩：白天約 18～25 度、早晚 12～16 度，午後常有一陣雨；山頂約 8～12 度、風大。'},
      {id:'b4',text:'🛵 過馬路：看準空隙慢慢直走不要停，機車會繞開您；突然停下或倒退反而危險。'},
      {id:'b5',text:'🚻 景點洗手間有時要付 2,000～5,000 盾，口袋留幾張小鈔。'},
      {id:'b6',text:'📶 山區訊號時好時壞，看到「離線中」不用緊張，重新整理或走到開闊處就會恢復。'}
    ]},
    {id:'lost',icon:'🧭',title:'走散怎麼辦',type:'notes',items:[
      {id:'l1',text:'1️⃣ 原地不動，站在明顯的店家或路口，先打給黃氏添（越南電話）。'},
      {id:'l2',text:'2️⃣ 打不通就把手機交給附近店員，出示「工具 → 緊急求助」裡的「我走散了」越文卡。'},
      {id:'l3',text:'3️⃣ 想直接回飯店，用「計程車回飯店卡」出示給司機；上車前先問價。'},
      {id:'l4',text:'🪪 護照影本、飯店名片、本網頁的走散卡，出門前請放在同一個隨身口袋。'},
      {id:'l5',text:'👥 兩人以上同行最安全；自由活動請務必約好回程時間與集合點。'}
    ]},
    {id:'money',icon:'💰',title:'金錢與購物',type:'notes',items:[
      {id:'m1',text:'💡 越南人習慣把「千」省略——店家說「năm mươi（50）」通常就是 50,000 盾；用「工具 → 越幣速算」按鈔票就能算。'},
      {id:'m2',text:'⚠️ 20,000 與 500,000 都是藍色系、10,000 與 200,000 都偏紅褐色，付錢前請數清楚後面幾個零。'},
      {id:'m3',text:'🛍️ 路邊攤開價通常可殺 3～5 成，明碼標價的店面比較穩妥；不想買就微笑說「Không cần, cảm ơn」。'},
      {id:'m4',text:'💵 導遊與司機小費由團上統一處理，個別不用再給；飯店行李員可給 10,000～20,000 盾。'},
      {id:'m5',text:'🏧 換匯：機場匯率較差，市區銀行或金飾店較好；ATM 提款每筆有手續費，一次領夠。'}
    ]},
    {id:'food',icon:'🍜',title:'吃喝與健康',type:'notes',items:[
      {id:'f1',text:'💧 自來水不能生飲，飯店每天有瓶裝水；冰塊盡量在餐廳或飯店才用。'},
      {id:'f2',text:'🍵 需要溫熱水、不加冰、不加香菜、不辣、吃素，都可用「越語圖卡」出示給店員。'},
      {id:'f3',text:'🌶️ 越南菜偏酸甜、香菜多；腸胃敏感的長輩前兩天先吃熟食、少吃生菜。'},
      {id:'f4',text:'⛰️ 番西邦山頂海拔高，動作放慢、多喝水；覺得頭暈就坐下休息，告訴身邊的人。'}
    ]}
  ]}
};

/* 示範用：先依名單順序排好桌次與車次，領隊可隨時「一鍵隨機分組」或手動調整 */
(function(){
  var ms = DEFAULTS.members.items;
  var meal = DEFAULTS.groups.scenarios[0], sh = DEFAULTS.groups.scenarios[1];
  ms.forEach(function(m,i){ meal.assign[m.id] = Math.floor(i/9); sh.assign[m.id] = i<17?0:1; });
})();
